name: flutter_sinusoidals
description: >-
  A flutter package that helps you to visualize sine waves as you desire.
  All basic waves are already supported, plus customized waves & some pre-defined waves.
version: 0.1.4
homepage: https://github.com/dungnv2602/flutter_sinusoidals

environment:
  sdk: '>=3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter